name: build check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 7 * * *'

jobs:
  install-and-run:
    strategy:
      matrix:
        ubuntu_version: [ubuntu:20.04, ubuntu:22.04, ubuntu:latest]
      fail-fast: true
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.ubuntu_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt install -y cmake build-essential git libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev

      - name: Build & Install cnr_common
        run: |
          chmod +x .github/workflows/github_workflow_cnr_common_install.sh 
          .github/workflows/github_workflow_cnr_common_install.sh
